# CMake generated Testfile for 
# Source directory: /home/gregor/minetest-android-test/lib/irrlichtmt/test
# Build directory: /home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ImageLoaderBMP-4bpp_v3 "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "16color-16bpp" "data/sample_4bpp_v3.bmp")
set_tests_properties(ImageLoaderBMP-4bpp_v3 PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;9;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderBMP-8bpp_v3 "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-16bpp" "data/sample_8bpp_v3.bmp")
set_tests_properties(ImageLoaderBMP-8bpp_v3 PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;13;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderBMP-8bpp_v3_rle "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-16bpp" "data/sample_8bpp_v3_rle.bmp")
set_tests_properties(ImageLoaderBMP-8bpp_v3_rle PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;15;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderBMP-24bpp_v3 "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-24bpp" "data/sample_24bpp_v3.bmp")
set_tests_properties(ImageLoaderBMP-24bpp_v3 PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;19;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderBMP-24bpp_v7 "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-24bpp" "data/sample_24bpp_v7.bmp")
set_tests_properties(ImageLoaderBMP-24bpp_v7 PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;20;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderPNG-8bpp "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-24bpp" "data/sample_8bpp.png")
set_tests_properties(ImageLoaderPNG-8bpp PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;22;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderPNG-24bpp "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-24bpp" "data/sample_24bpp.png")
set_tests_properties(ImageLoaderPNG-24bpp PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;23;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderTGA-8bpp_up "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-32bpp" "data/sample_8bpp_up.tga")
set_tests_properties(ImageLoaderTGA-8bpp_up PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;25;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderTGA-8bpp_down "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-32bpp" "data/sample_8bpp_down.tga")
set_tests_properties(ImageLoaderTGA-8bpp_down PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;26;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderTGA-24bpp_up "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-24bpp" "data/sample_24bpp_up.tga")
set_tests_properties(ImageLoaderTGA-24bpp_up PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;29;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderTGA-24bpp_down "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-24bpp" "data/sample_24bpp_down.tga")
set_tests_properties(ImageLoaderTGA-24bpp_down PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;30;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderTGA-24bpp_rle_up "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-24bpp" "data/sample_24bpp_rle_up.tga")
set_tests_properties(ImageLoaderTGA-24bpp_rle_up PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;31;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
add_test(ImageLoaderTGA-24bpp_rle_down "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/bin/Linux/image_loader_test" "30color-24bpp" "data/sample_24bpp_rle_down.tga")
set_tests_properties(ImageLoaderTGA-24bpp_rle_down PROPERTIES  WORKING_DIRECTORY "/home/gregor/minetest-android-test/lib/irrlichtmt/test" _BACKTRACE_TRIPLES "/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;6;add_test;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;32;test_image_loader;/home/gregor/minetest-android-test/lib/irrlichtmt/test/CMakeLists.txt;0;")
