# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.25)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS IrrlichtMt::IrrlichtMt)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target IrrlichtMt::IrrlichtMt
add_library(IrrlichtMt::IrrlichtMt STATIC IMPORTED)

set_target_properties(IrrlichtMt::IrrlichtMt PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "IRRLICHT_API="
  INTERFACE_INCLUDE_DIRECTORIES "/home/gregor/minetest-android-test/lib/irrlichtmt/include/;/home/gregor/minetest-android-test/lib/irrlichtmt/source/Irrlicht"
  INTERFACE_LINK_LIBRARIES "/usr/lib64/libz.so;/usr/lib64/libjpeg.so;/usr/lib64/libpng.so;\$<LINK_ONLY:\$<\$<BOOL:ON>:SDL2::SDL2main;SDL2::SDL2>>;\$<LINK_ONLY:\$<\$<BOOL:TRUE>:/usr/lib64/libOpenGL.so;/usr/lib64/libGLX.so;/usr/lib64/libGLU.so>>;\$<LINK_ONLY:\$<\$<BOOL:>:>>;\$<LINK_ONLY:\$<\$<BOOL:>:>>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:Android>:-landroid -llog>>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:Windows>:gdi32>>;\$<LINK_ONLY:\$<\$<PLATFORM_ID:Windows>:winmm>>;\$<LINK_ONLY:\$<\$<BOOL:FALSE>:>>;\$<LINK_ONLY:\$<\$<BOOL:FALSE>:>>"
)

# Import target "IrrlichtMt::IrrlichtMt" for configuration "Release"
set_property(TARGET IrrlichtMt::IrrlichtMt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(IrrlichtMt::IrrlichtMt PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/gregor/minetest-android-test/cmkbld/lib/irrlichtmt/lib/Linux/libIrrlichtMt.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
